DROP TABLE IF EXISTS public.messages;
DROP TABLE IF EXISTS public.profiles;

create table
  public.profiles (
    id uuid not null,
    name text null,
    email text not null,
    avatar_url text null,
    constraint profiles_pkey primary key (id),
    constraint profiles_email_key unique (email),
    constraint profiles_id_fkey foreign key (id) references auth.users (id) on delete cascade
  ) tablespace pg_default;


create table
  public.messages (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    text text null,
    "user" uuid null,
    constraint messages_pkey primary key (id),
    constraint messages_user_fkey foreign key ("user") references profiles (id) on delete cascade
  ) tablespace pg_default;
